import fs from 'node:fs';
const base='src/pages/';
let s=fs.readFileSync(base+'CommissionDetail.tsx','utf8');
s=s.replace("subtitle=\"Внешний участник\"",'subtitle="Участник из справочника"');
const a=s.indexOf("{tab === 'chairman' &&");const b=s.indexOf("{tab === 'programs' &&",a);
s=s.slice(0,a)+`{tab === 'chairman' && <><SectionHeading eyebrow="ПРЕДСЕДАТЕЛЬ КОМИССИИ" title="Сведения о председателе" description="Подробная карточка заполняется в исходных данных."/>{chair ? <><div className="profile-person"><Avatar person={chair}/><div><h3>{chair.name}</h3><p>{chair.position} · {chair.organization}</p></div></div><p className="chair-summary">{chair.degree} · {chair.rank}</p><button className="button primary" onClick={() => navigate('/data/people/' + (draft.type === 'complex' ? 'complex' : 'chairmen') + '?person=' + encodeURIComponent(chair.id))}>Открыть карточку в справочнике <ArrowUpRight size={16}/></button></> : <Empty title="Сначала назначьте председателя" action={<button className="button primary" onClick={() => setPicker('chairman')}>Выбрать председателя</button>}>Выберите участника из справочника.</Empty>}</>}`+s.slice(b);
s=s.replace("['chairman', 'Карточка председателя'","['chairman', 'Председатель'");
const fa=s.indexOf('function ProfileForm(');const fb=s.indexOf('function MetadataModal(',fa);s=s.slice(0,fa)+s.slice(fb);
s=s.replace("'При выборе другого председателя сведения о его образовании и опыте нужно будет заполнить заново.'","'Подробные сведения о председателе заполняются в его карточке в исходных данных.'");
fs.writeFileSync(base+'CommissionDetail.tsx',s);
s=fs.readFileSync(base+'PeopleTable.tsx','utf8');
s=s.replace("import { useState }", "import { useEffect, useState }");
s=s.replace("Link, useParams", "Link, useParams, useSearchParams");
s="import { ChairmanCard } from '../components/ChairmanCard';\n"+s;
s=s.replace('type Entry =','export type Entry =');
s=s.replace("const { category='external' }=useParams();", "const { category='external' }=useParams(); const [params,setParams]=useSearchParams();");
s=s.replace("if(!titles[category])",`useEffect(()=>{ const personId=params.get('person'); const card=params.get('card'); const found=(all[category]??[]).find(e=>card?e.id===card:personId?e.personId===personId:false); setEntry(found?structuredClone(found):null); setQuery(''); setSphere(''); },[category,params]);
 if(!titles[category])`);
s=s.replace("setEntry(null);notify('Карточка сохранена в демо');","notify('Карточка сохранена в демо');return true;");
s=s.replace("catch{notify('Не удалось сохранить: хранилище браузера недоступно');}};", "catch{notify('Не удалось сохранить: хранилище браузера недоступно');return false;}};");
s=s.replace('return <div className="page-enter hub-page">',`if(entry && person && !external) return <ChairmanCard key={entry.id} entry={entry} person={person} complex={category==='complex'} onChange={setEntry} onSave={save} onBack={()=>setParams({})}/>;
 return <div className="page-enter hub-page">`);
s=s.replace('onClick={()=>setEntry(structuredClone(e))}',"onClick={()=>setParams({card:e.id})}");
s=s.replace('onClose={()=>setEntry(null)}','onClose={()=>setParams({})}').replace('onClick={()=>setEntry(null)}','onClick={()=>setParams({})}');
s=s.replace('<div className="people-table-shell">',`{params.get('person')&&!entry&&<p className="info-note">Для выбранного человека ещё нет карточки в этой демонстрационной таблице. Ниже доступны существующие записи.</p>}<div className="people-table-shell">`);
fs.writeFileSync(base+'PeopleTable.tsx',s);
