import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{const p=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});p.setDefaultTimeout(8000);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5174/login');await p.getByRole('button',{name:'Заполнить данные для входа'}).click();await p.getByRole('button',{name:'Войти в рабочее пространство'}).click();
await p.goto('http://127.0.0.1:5174/data/catalog/directions');const row=p.getByRole('row').filter({hasText:'38.03.02'});await row.getByRole('link',{name:'2 программ'}).click();await expect(p.locator('.catalog-table tbody tr')).toHaveCount(2);await p.getByRole('button',{name:'Добавить',exact:true}).click();const d=p.getByRole('dialog');await d.getByLabel('Код программы',{exact:true}).fill('38.03.02.99');await d.getByLabel('Название программы / профиля',{exact:true}).fill('Новая программа');await d.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(p.locator('.catalog-table tbody tr')).toHaveCount(3);await p.reload();await expect(p.locator('.catalog-table tbody tr')).toHaveCount(3);
await p.getByRole('link',{name:'Направления подготовки',exact:true}).click();await p.getByRole('button',{name:'Удалить 38.03.02',exact:true}).click();await p.getByRole('dialog').getByRole('button',{name:'Удалить',exact:true}).click();await expect(p.getByText('Сначала перенесите или удалите программы этого направления.',{exact:false})).toBeVisible();await p.getByRole('button',{name:'Отмена',exact:true}).click();
await p.goto('http://127.0.0.1:5174/data/catalog/schools');await expect(p.locator('.catalog-table')).toContainText('И.о. директора');await p.getByRole('button',{name:'Изменить Высшая школа бизнеса',exact:true}).click();await p.getByRole('textbox',{name:'Должность директора / и.о.',exact:true}).fill('И.о. директора');await p.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();
await p.goto('http://127.0.0.1:5174/data/catalog/teachers');await expect(p.locator('.catalog-table tbody tr')).toHaveCount(5);await p.getByRole('combobox',{name:'Фильтр справочника'}).click();await p.getByRole('option',{name:'Высшая школа производственного менеджмента',exact:true}).click();await expect(p.locator('.catalog-table tbody tr')).toHaveCount(2);
await p.goto('http://127.0.0.1:5174/data/catalog/disciplines');await p.getByRole('button',{name:'Добавить',exact:true}).click();await p.getByRole('textbox',{name:'Название дисциплины',exact:true}).fill('Тестовая дисциплина');await p.getByRole('dialog').getByRole('combobox',{name:'Высшая школа',exact:true}).click();await p.getByRole('option',{name:'Высшая школа бизнеса',exact:true}).click();await p.getByRole('combobox',{name:'Уровень образования',exact:true}).click();await p.getByRole('option',{name:'Магистратура',exact:true}).click();await p.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();await expect(p.locator('.catalog-table')).toContainText('Тестовая дисциплина');await p.screenshot({path:'artifacts/catalog.png',fullPage:true});
await p.setViewportSize({width:390,height:844});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Page overflow');if(errors.length)throw Error(errors.join(';'));console.log('PASS: five tables, relations, create/edit/persistence/filters/mobile');
}finally{await browser.close();}
