import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.setDefaultTimeout(8000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5174/login');await page.getByRole('button',{name:'Заполнить данные для входа'}).click();await page.getByRole('button',{name:'Войти в рабочее пространство'}).click();await page.getByRole('heading',{name:'С чего начнём?',exact:true}).waitFor();console.log(await page.locator('.section-help-bar').innerText());await page.getByRole('button',{name:'Как устроена система',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Закрыть окно'}).click();
await page.getByRole('link',{name:'Архив',exact:true}).click();await expect(page.getByRole('button',{name:'Как работать с архивом',exact:true})).toBeVisible();await page.locator('.archive-item-name').filter({hasText:'2024–2025 учебный год'}).waitFor();await page.screenshot({path:'artifacts/archive.png',fullPage:true});
await page.getByRole('button',{name:'Создать папку',exact:true}).click();await page.getByRole('textbox',{name:'Название',exact:true}).fill('Тестовая папка');await page.getByRole('dialog').getByRole('button',{name:'Создать папку',exact:true}).click();await page.getByRole('button',{name:'Тестовая папка 0 объектов',exact:true}).click();await expect(page.getByText('В этой папке пока пусто',{exact:true})).toBeVisible();
await page.getByLabel('Выбрать файлы для архива',{exact:true}).setInputFiles([{name:'пример.txt',mimeType:'text/plain',buffer:Buffer.from('Проверка содержимого')},{name:'пример.txt',mimeType:'text/plain',buffer:Buffer.from('Второй файл')}]);await page.getByRole('button',{name:'Добавить в архив',exact:true}).click();await expect(page.getByRole('button',{name:'Скачать пример (1).txt',exact:true})).toBeVisible();await page.reload();
const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать пример.txt',exact:true}).click();const download=await downloading;if(await fs.readFile(await download.path(),'utf8')!=='Проверка содержимого')throw Error('File contents changed');
await page.getByRole('button',{name:'Переименовать пример.txt',exact:true}).click();await page.getByRole('textbox',{name:'Название',exact:true}).fill('итог.txt');await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('button',{name:'Скачать итог.txt',exact:true})).toBeVisible();
await page.getByRole('button',{name:'На уровень выше',exact:true}).click();await page.getByRole('button',{name:'Удалить Тестовая папка',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Удалить',exact:true}).click();await expect(page.getByRole('button',{name:'Удалить Тестовая папка',exact:true})).toHaveCount(0);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/archive-mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Mobile overflow');if(errors.length)throw Error(errors.join(';'));console.log('PASS: archive create/upload/duplicates/persistence/download/rename/recursive delete/help/mobile');
}finally{await browser.close();}
