import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
page.setDefaultTimeout(8000); const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5174/login');
await page.getByRole('button',{name:'Заполнить данные для входа'}).click();
await page.getByRole('button',{name:'Войти в рабочее пространство'}).click();
await page.getByRole('heading',{name:'С чего начнём?'}).waitFor();
await fs.mkdir('artifacts',{recursive:true});
await page.screenshot({path:'artifacts/home.png',fullPage:true});
await page.locator('.module-grid').getByRole('link').filter({hasText:'Исходные данные'}).click();
await page.locator('.hub-section.live').click();
await page.getByRole('heading',{name:'Люди',exact:true}).waitFor();
await page.screenshot({path:'artifacts/people.png',fullPage:true});
console.log('people'); await page.locator('.people-hub-grid a').filter({hasText:'Председатели комплексных ГЭК'}).click();
console.log('education'); await page.getByRole('row').filter({hasText:'Кузнецова'}).getByRole('button',{name:'Открыть'}).click();
await page.getByLabel('Публикации по программе',{exact:true}).fill('Демонстрационная публикация');
if(await page.getByLabel('Кандидат является',{exact:true}).count())throw Error('Education form includes business fields');
if(await page.getByRole('checkbox').count()!==4)throw Error('Complex school multi-selection missing');
await page.getByRole('button',{name:'Сохранить',exact:true}).click();
await page.reload();
console.log('education'); await page.getByRole('row').filter({hasText:'Кузнецова'}).getByRole('button',{name:'Открыть'}).click();
if(await page.getByLabel('Публикации по программе',{exact:true}).inputValue()!=='Демонстрационная публикация')throw Error('Save failed');
await page.getByRole('button',{name:'Закрыть окно'}).click();
await page.getByRole('row').filter({hasText:'Громов'}).getByRole('button',{name:'Открыть'}).click();
await page.getByLabel('Кандидат является',{exact:true}).waitFor();
if(await page.getByLabel('Публикации по программе',{exact:true}).count())throw Error('Business form includes education fields');
await page.getByRole('button',{name:'Закрыть окно'}).click();
await page.getByRole('link',{name:'Председатели ГЭК',exact:true}).click();
await page.getByRole('heading',{name:'Председатели ГЭК',exact:true}).waitFor();
await page.getByRole('link',{name:'Внешние члены ГЭК',exact:true}).click();
await page.getByRole('heading',{name:'Внешние члены ГЭК',exact:true}).waitFor();
await page.getByRole('link',{name:'Комиссии ГЭК',exact:true}).click();
await page.locator('.module-card').filter({hasText:'Формирование и печать'}).click();
await page.locator('.document-school select').selectOption('management');
await page.locator('.print-actions section').filter({hasText:'Состав председателей ГЭК'}).getByRole('button',{name:'По выбранной школе'}).click();
await page.getByRole('dialog').waitFor();
await page.emulateMedia({media:'print'});
if(!await page.locator('.document-paper').isVisible())throw Error('Print document hidden');
await page.screenshot({path:'artifacts/print.png',fullPage:true});
await page.emulateMedia({media:'screen'});
await page.getByRole('button',{name:'Закрыть окно'}).click();
console.log('mobile'); await page.getByRole('link',{name:'Главная',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Mobile overflow');
await page.getByRole('button',{name:'Открыть меню'}).click();
await page.getByRole('link',{name:'Люди',exact:true}).click();
await page.getByRole('heading',{name:'Люди',exact:true}).waitFor();
console.log(JSON.stringify({result:'PASS',errors}));
await browser.close();


