<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
require dirname(__DIR__).'/src/catalog.php';
require dirname(__DIR__).'/src/people.php';

// All writes target session-local TEMP tables. No public rows, sequences or schema
// are changed. Every source table is shadowed, including legacy relations without FK.
$tables=rows("SELECT tablename FROM pg_tables WHERE schemaname='public'");
$serials=rows("SELECT c.relname AS tbl,a.attname AS col FROM pg_class c
    JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid
    JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum
    WHERE n.nspname='public' AND pg_get_expr(d.adbin,d.adrelid) LIKE 'nextval(%'");
$foreignKeys=rows("SELECT c.relname AS tbl, pg_get_constraintdef(k.oid) AS definition
    FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE k.contype='f' AND n.nspname='public'");
foreach($tables as $table) {
    $name=pg_escape_identifier($table['tablename']);
    query("CREATE TEMP TABLE $name (LIKE public.$name INCLUDING IDENTITY INCLUDING INDEXES INCLUDING CONSTRAINTS)");
}
query('SET search_path TO pg_temp, public');
foreach($serials as $serial) {
    $table=pg_escape_identifier($serial['tbl']);$column=pg_escape_identifier($serial['col']);
    query("ALTER TABLE pg_temp.$table ALTER COLUMN $column ADD GENERATED BY DEFAULT AS IDENTITY");
}
foreach($foreignKeys as $fk) {
    $table=pg_escape_identifier($fk['tbl']);
    $definition=str_replace('REFERENCES public.','REFERENCES pg_temp.',$fk['definition']);
    query("ALTER TABLE pg_temp.$table ADD $definition");
}
function check(bool $condition,string $message): void {if(!$condition)throw new RuntimeException($message);}
function expectError(string $code,callable $operation): void {
    try {$operation();} catch(ApiError $error) {check($error->errorCode===$code,"Expected $code, got ".$error->errorCode);return;}
    throw new RuntimeException("Expected error $code");
}
function catalogRow(string $kind,string $id): array {
    $pk=catalogDefinitions()[$kind]['pk'];
    foreach(catalogSnapshot()[$kind] as $row)if($row[$pk]===$id)return $row;
    throw new RuntimeException('Missing catalog row');
}
function cardRow(string $kind,string $id): array {
    foreach(peopleSnapshot()['entries'][$kind] as $row)if($row['id']===$id)return $row;
    throw new RuntimeException('Missing card');
}

query("INSERT INTO levels(id_level,level) VALUES(1,'Бакалавриат')");
$school=saveCatalog('schools',['name_school'=>'Тестовая школа','short'=>'ТШ','chief_role'=>'И.о. директора'])['id'];
$school2=saveCatalog('schools',['name_school'=>'Вторая школа','short'=>'ВШ'])['id'];
check($school!==$school2,'School IDs must be different');
$direction=saveCatalog('directions',['number_direction'=>'01.03.05','name_direction'=>'Статистика','id_level'=>'1'])['id'];
$program=saveCatalog('programs',['id_program'=>'01.03.05_01','name_program'=>'Программа 1','id_direction'=>$direction])['id'];
saveCatalog('programs',['id_program'=>'01.03.05_02','name_program'=>'Программа 2','id_direction'=>$direction]);
check(count(catalogSnapshot()['programs'])===2,'One direction has two programs');
expectError('DUPLICATE',fn()=>saveCatalog('programs',['id_program'=>'01.03.05_01','name_program'=>'Дубль','id_direction'=>$direction]));
expectError('INVALID_REFERENCE',fn()=>saveCatalog('teachers',['id_teacher'=>'bad','name_teacher'=>'Тест','id_school'=>'99999']));
expectError('VALIDATION',fn()=>saveCatalog('teachers',['name_teacher'=>'Тест','id_school'=>$school]));
$teacher=saveCatalog('teachers',['id_teacher'=>'00123','name_teacher'=>'Тестовый Преподаватель','id_school'=>$school])['id'];
check($teacher==='00123','Tab number must retain leading zeros');
$discipline=saveCatalog('disciplines',['name_discipline'=>'Математика','id_school'=>$school,'id_level'=>'1'])['id'];
$row=catalogRow('disciplines',$discipline);
saveCatalog('disciplines',[...$row,'id'=>$discipline,'name_discipline'=>'Высшая математика']);
expectError('STALE_RECORD',fn()=>saveCatalog('disciplines',[...$row,'id'=>$discipline,'name_discipline'=>'Потерянная правка']));
expectError('IN_USE',fn()=>deleteCatalog('schools',['id'=>$school,'version'=>catalogRow('schools',$school)['version']]));
expectError('IN_USE',fn()=>deleteCatalog('directions',['id'=>$direction,'version'=>catalogRow('directions',$direction)['version']]));

$external=savePeople('external',['person'=>['name'=>'Тестовый Внешний','organization'=>'Организация']])['id'];
$chair=savePeople('chairmen',['personId'=>'member:'.$external,'sphere'=>'Бизнес','schoolIds'=>[$school],'values'=>['career_activity'=>'Практика','publications'=>'Сохранённые сведения']])['id'];
expectError('DUPLICATE',fn()=>savePeople('complex',['personId'=>'member:'.$external,'sphere'=>'Образование','schoolIds'=>[]]));
expectError('IN_USE',fn()=>deletePeople('external',['id'=>$external,'version'=>cardRow('external',$external)['version']]));
$old=cardRow('chairmen',$chair);
savePeople('chairmen',[...$old,'schoolIds'=>[$school2],'values'=>['career_activity'=>'Новая практика']]);
$new=cardRow('chairmen',$chair);
check($new['schoolIds']===[$school2],'School association must be replaced');
check($new['values']['publications']==='Сохранённые сведения','Omitted sphere fields must survive');
expectError('STALE_RECORD',fn()=>savePeople('chairmen',$old));
expectError('INVALID_REFERENCE',fn()=>savePeople('chairmen',[...$new,'schoolIds'=>['99999']]));
check(cardRow('chairmen',$chair)['schoolIds']===[$school2],'Failed save must not partially change card');
$complex=savePeople('complex',['personId'=>'teacher:'.$teacher,'sphere'=>'Образование','schoolIds'=>[$school,$school2],'values'=>['lectures'=>'Лекции']])['id'];
$complexRow=cardRow('complex',$complex);
check(str_starts_with($complexRow['personId'],'member:'),'Teacher must link to sec_member');
check(count(rows('SELECT * FROM sec_member WHERE employee_number=$1',[$teacher]))===1,'No duplicate teacher member');
savePeople('complex',[...$complexRow,'schoolIds'=>[$school2]]);
check(cardRow('complex',$complex)['schoolIds']===[$school2],'Complex selection replaces schools, does not toggle');
query('INSERT INTO sec_program(id_predsedatel_sc,id_program) VALUES($1,$2)',[$complex,'01.03.05_01']);
saveCatalog('programs',[...catalogRow('programs',$program),'id'=>$program,'id_program'=>'01.03.05_03']);
check(rows('SELECT id_program FROM sec_program')[0]['id_program']==='01.03.05_03','Code-based program relation survives rename');
expectError('IN_USE',fn()=>deleteCatalog('programs',['id'=>$program,'version'=>catalogRow('programs',$program)['version']]));
query('INSERT INTO sec(chairman,id_school) VALUES($1,$2)',[$external,$school]);
expectError('IN_USE',fn()=>deletePeople('chairmen',cardRow('chairmen',$chair)));
query('DELETE FROM sec');
deletePeople('chairmen',cardRow('chairmen',$chair));
deletePeople('external',cardRow('external',$external));
deletePeople('complex',cardRow('complex',$complex));
check(count(rows('SELECT * FROM sec_program'))===0,'Owned card links removed');
check(count(rows('SELECT * FROM sec_member WHERE employee_number=$1',[$teacher]))===1,'Deleting a card preserves the member');
deleteCatalog('disciplines',['id'=>$discipline,'version'=>catalogRow('disciplines',$discipline)['version']]);
check(count(catalogSnapshot()['disciplines'])===0,'Unlinked record deleted');
$orphan=insertRecord('sec_predsedatel_s',['sm_id'=>'99999','area'=>'Бизнес','complex'=>'f'],'id_predsedatel_sc');
$snapshot=peopleSnapshot();
check(count(array_filter($snapshot['people'],fn($person)=>($person['missing']??false)))===1,'Orphan cards must stay visible');
expectError('MISSING_PERSON',fn()=>savePeople('chairmen',[...cardRow('chairmen',$orphan),'schoolIds'=>[$school]]));
echo "PASS: isolated CRUD, required fields, references, duplicates, stale edits, atomic school links, sphere fields, teacher identity, program codes, safe deletion. Public DB unchanged.".PHP_EOL;
