import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Archive as ArchiveIcon, Folder, FolderPlus, FileText, Upload, Download, Pencil, Trash2, Search, ChevronRight, ArrowLeft, ArrowDownUp, X, Check } from 'lucide-react';
import { Modal, Field, Confirm, Empty } from '../components/ui';
import { readArchive, writeArchive, uniqueName, descendants, type ArchiveItem } from '../data/archive';
import { useStore } from '../store';
const size=(n:number)=>n<1024?`${n} Б`:n<1048576?`${(n/1024).toFixed(1)} КБ`:`${(n/1048576).toFixed(1)} МБ`;
export function Archive(){
 const [params,setParams]=useSearchParams();const folder=params.get('folder');const {notify}=useStore();const [items,setItems]=useState<ArchiveItem[]>([]);const [loading,setLoading]=useState(true);const [failure,setFailure]=useState('');const [query,setQuery]=useState('');const [sort,setSort]=useState<'name'|'date'>('name');const [edit,setEdit]=useState<ArchiveItem|'new'|null>(null);const [name,setName]=useState('');const [error,setError]=useState('');const [deleting,setDeleting]=useState<ArchiveItem|null>(null);const [uploads,setUploads]=useState<File[]|null>(null);const [busy,setBusy]=useState(false);const [dragging,setDragging]=useState(false);const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{let alive=true;readArchive().then(v=>{if(alive)setItems(v);}).catch(()=>{if(alive)setFailure('Не удалось открыть локальное хранилище архива. Разрешите хранение данных в браузере и обновите страницу.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[]);
 useEffect(()=>setQuery(''),[folder]);
 const current=items.find(i=>i.id===folder&&i.kind==='folder');const parents:ArchiveItem[]=[];let p=current;while(p&&!parents.some(v=>v.id===p!.id)){parents.unshift(p);p=items.find(i=>i.id===p?.parent);}
 const siblings=items.filter(i=>i.parent===folder);const shown=siblings.filter(i=>i.name.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru'))).sort((a,b)=>Number(b.kind==='folder')-Number(a.kind==='folder')||(sort==='date'?b.updated-a.updated:a.name.localeCompare(b.name,'ru')));
 const go=(id:string|null)=>setParams(id?{folder:id}:{});
 const commit=async(next:ArchiveItem[],deleted:string[]=[])=>{setBusy(true);try{await writeArchive(next,deleted);setItems(old=>[...old.filter(i=>!deleted.includes(i.id)&&!next.some(n=>n.id===i.id)),...next]);return true;}catch{setError('Не удалось сохранить. Возможно, в браузере недостаточно места.');notify('Изменения не сохранены');return false;}finally{setBusy(false);}};
 const saveName=async()=>{const value=name.trim();if(!value||/[\\/:*?"<>|]/.test(value)||value==='.'||value==='..'){setError('Введите имя без символов \\ / : * ? " < > |');return;}if(siblings.some(i=>i.id!==(edit==='new'?null:edit?.id)&&i.name.toLocaleLowerCase('ru')===value.toLocaleLowerCase('ru'))){setError('Такое имя уже есть в этой папке');return;}const item:ArchiveItem=edit==='new'?{id:crypto.randomUUID(),name:value,parent:folder,kind:'folder',updated:Date.now()}:{...edit as ArchiveItem,name:value,updated:Date.now()};if(await commit([item])){setEdit(null);notify(edit==='new'?'Папка создана':'Название изменено');}};
 const upload=async()=>{if(!uploads)return;const next:ArchiveItem[]=[];uploads.forEach(f=>next.push({id:crypto.randomUUID(),parent:folder,name:uniqueName(f.name,[...siblings,...next]),kind:'file',updated:Date.now(),blob:f}));if(await commit(next)){setUploads(null);notify(`Добавлено файлов: ${next.length}`);}};
 const download=(item:ArchiveItem)=>{if(!item.blob)return;const url=URL.createObjectURL(item.blob);const a=document.createElement('a');a.href=url;a.download=item.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);};
 if(loading)return <div className="scope-note" role="status">Открываем архив…</div>;
 if(failure)return <Empty title="Архив недоступен">{failure}</Empty>;
 if(folder&&!current)return <Empty title="Папка не найдена" action={<button className="button primary" onClick={()=>go(null)}>В корень архива</button>}>Возможно, папка была удалена.</Empty>;
 return <div className="page-enter hub-page archive-page"><div className="page-heading"><div><div className="heading-eyebrow"><ArchiveIcon size={16}/> ДОКУМЕНТЫ И МАТЕРИАЛЫ</div><h1>Архив</h1><p>Сохраняйте документы по папкам и находите нужное без лишних переходов.</p></div><div className="button-row"><button className="button secondary" onClick={()=>{setEdit('new');setName('Новая папка');setError('');}}><FolderPlus size={17}/> Создать папку</button><button className="button primary" onClick={()=>fileInput.current?.click()}><Upload size={17}/> Добавить файлы</button></div></div><input ref={fileInput} className="sr-only" type="file" multiple aria-label="Выбрать файлы для архива" onChange={e=>{setUploads(Array.from(e.target.files??[]));setError('');e.target.value='';}}/>
 <div className="archive-layout"><section className={`archive-workspace ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragging(false);}} onDrop={e=>{e.preventDefault();setDragging(false);const files=Array.from(e.dataTransfer.files);if(files.length){setUploads(files);setError('');}}}>
 <div className="archive-path"><button aria-label="На уровень выше" disabled={!folder} onClick={()=>go(current?.parent??null)}><ArrowLeft size={17}/></button><nav aria-label="Путь в архиве"><button onClick={()=>go(null)}>Все файлы</button>{parents.map(i=><span key={i.id}><ChevronRight size={14}/><button onClick={()=>go(i.id)} aria-current={i.id===folder?'page':undefined}>{i.name}</button></span>)}</nav></div>
 <div className="archive-toolbar"><div className="search-field"><Search size={17}/><input aria-label="Поиск в текущей папке" placeholder="Поиск в этой папке" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" aria-label="Очистить поиск" onClick={()=>setQuery('')}><X size={14}/></button>}</div><button className="text-button" onClick={()=>setSort(sort==='name'?'date':'name')}><ArrowDownUp size={15}/>{sort==='name'?'По названию':'Сначала новые'}</button></div>
 <div className="archive-table"><div className="archive-table-head"><span>Название</span><span>Изменён</span><span>Размер</span><span/></div>{shown.map(i=><article className="archive-row" key={i.id}><button className="archive-item-name" onClick={()=>i.kind==='folder'?go(i.id):download(i)}><span className={`archive-file-icon ${i.kind}`} >{i.kind==='folder'?<Folder size={24}/>:<FileText size={23}/>}</span><span><strong>{i.name}</strong><small>{i.kind==='folder'?`${items.filter(c=>c.parent===i.id).length} объектов`:i.name.split('.').pop()?.toUpperCase()+' · файл'}</small></span></button><span className="archive-date">{new Date(i.updated).toLocaleDateString('ru-RU')}</span><span className="archive-size">{i.kind==='file'?size(i.blob?.size??0):'—'}</span><div className="archive-row-actions">{i.kind==='file'&&<button className="icon-button" aria-label={`Скачать ${i.name}`} title="Скачать" onClick={()=>download(i)}><Download size={16}/></button>}<button className="icon-button" aria-label={`Переименовать ${i.name}`} title="Переименовать" onClick={()=>{setEdit(i);setName(i.name);setError('');}}><Pencil size={15}/></button><button className="icon-button archive-delete" aria-label={`Удалить ${i.name}`} title="Удалить" onClick={()=>{setDeleting(i);setError('');}}><Trash2 size={15}/></button></div></article>)}</div>
 {!shown.length&&<Empty title={query?'Ничего не найдено':'В этой папке пока пусто'}>{query?'Попробуйте другое название.':'Добавьте файлы или создайте папку для документов.'}</Empty>}
 <button className="archive-drop" onClick={()=>fileInput.current?.click()}><Upload size={21}/><span><strong>{dragging?'Отпустите файлы здесь':'Перетащите файлы в эту область'}</strong><small>или нажмите, чтобы выбрать на компьютере</small></span></button><footer className="archive-count">{shown.length} объектов {query&&`из ${siblings.length}`}<span>{current?.name??'Корень архива'}</span></footer></section>
 <aside className="archive-aside"><span className="module-icon"><Folder size={25}/></span><h2>Порядок в документах</h2><p>Соберите материалы одной кампании или комиссии в отдельную папку.</p><div className="archive-tip"><Check size={16}/><span>Файлы добавляются в открытую папку.</span></div><div className="archive-tip"><Check size={16}/><span>При совпадении имён добавляется номер — существующий файл сохраняется.</span></div><div className="archive-tip"><Check size={16}/><span>Папки можно открывать, переименовывать и удалять вместе с содержимым.</span></div><div className="archive-demo-note">Демо: файлы хранятся только в этом браузере и не отправляются на сервер.</div></aside></div>
 {edit&&<Modal title={edit==='new'?'Новая папка':'Переименовать'} subtitle={`Расположение: ${current?.name??'Все файлы'}`} onClose={()=>{if(!busy)setEdit(null);}} footer={<><button className="button secondary" disabled={busy} onClick={()=>setEdit(null)}>Отмена</button><button className="button primary" disabled={busy} form="archive-name" type="submit">{busy?'Сохранение…':edit==='new'?'Создать папку':'Сохранить'}</button></>}><form id="archive-name" onSubmit={e=>{e.preventDefault();void saveName();}}><Field label="Название" error={error}><input aria-label="Название" autoFocus value={name} onChange={e=>{setName(e.target.value);setError('');}} maxLength={180} required/></Field></form></Modal>}
 {uploads&&<Modal title="Добавить файлы" subtitle={`В папку: ${current?.name??'Все файлы'}`} onClose={()=>{if(!busy)setUploads(null);}} footer={<><span className="muted">{uploads.length} файлов</span><button className="button secondary" disabled={busy} onClick={()=>setUploads(null)}>Отмена</button><button className="button primary" disabled={busy||!uploads.length} onClick={()=>void upload()}>{busy?'Сохранение…':'Добавить в архив'}</button></>}><div className="archive-upload-list">{uploads.map((f,i)=><div key={i}><FileText size={18}/><span>{uniqueName(f.name,siblings)}<small>{size(f.size)}</small></span><button className="icon-button" aria-label={`Убрать файл ${f.name}`} disabled={busy} onClick={()=>setUploads(uploads.filter((_,index)=>index!==i))}><X size={16}/></button></div>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}</Modal>}
 {deleting&&<Confirm title={`Удалить ${deleting.kind==='folder'?'папку':'файл'}?`} confirmLabel={busy?'Удаление…':'Удалить'} danger onClose={()=>{if(!busy)setDeleting(null);}} onConfirm={()=>{if(busy)return;void(async()=>{if(await commit([],descendants(deleting.id,items))){setDeleting(null);notify('Удалено из архива');}})();}}>«{deleting.name}»{deleting.kind==='folder'?` и всё содержимое (${descendants(deleting.id,items).length-1} объектов)` : ''} будут удалены из локального архива. {error}</Confirm>}
 </div>;
}
