import { useGek } from '../data/gek';
import { PageTitle } from '../components/PageTitle';
import { AppSelect } from '../components/AppSelect';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowUpRight, BookOpen, Layers3, GraduationCap, Database, Archive, UsersRound, Building2, LibraryBig, Files, Printer, BriefcaseBusiness, UserRoundCheck, Network } from 'lucide-react';
import { useStore } from '../store';
import { schools, schoolName, type Commission, csvCell, downloadText } from '../data/model';
import { people } from '../data/seed';
import { DocumentPreview } from '../components/Documents';
import { Modal } from '../components/ui';
const modules = [
 { title:'Разработка и корректировка ООП', description:'Образовательные программы и работа с их содержанием.', to:'/oop', icon:BookOpen, available:true },
 { title:'Формирование аттестационных комиссий', description:'Подготовка составов аттестационных комиссий.', to:'/attestation', icon:Layers3, available:true },
 { title:'Формирование государственных экзаменационных комиссий', description:'Составы ГЭК, карточки председателей и печатные формы.', to:'/gek', icon:GraduationCap, available:true },
 { title:'Исходные данные', description:'Структура университета, участники ГЭК, направления, программы и дисциплины.', to:'/data', icon:Database, available:true },
 { title:'Архив', description:'Материалы и документы прошлых кампаний.', to:'/archive', icon:Archive, available:true },
];
export function Home() { return <div className="page-enter hub-page"><div className="hub-welcome"><PageTitle>Разделы системы</PageTitle><p>Автоматизированная система поддержки образовательного процесса ИПМЭиТ</p></div><div className="module-grid">{modules.map((m,i) => <Link to={m.to} key={m.to} className={`module-card ${m.available ? 'available' : ''}`}><div className="module-top"><span className="module-icon"><m.icon size={27}/></span><span className="module-number">0{i+1}</span></div><h2>{m.title}</h2><p>{m.description}</p><footer><span>{m.available ? 'Открыть раздел' : 'Обзор раздела'}</span><ArrowUpRight size={18}/></footer></Link>)}</div></div>; }
export function Unavailable() { const { module } = useParams(); const m=modules.find(m=>m.to===`/${module}`); return <div className="page-enter hub-page"><Link className="text-button" to="/">← Главная</Link><div className="hub-welcome"><span className="eyebrow">РАЗДЕЛ РАБОЧЕГО ПРОСТРАНСТВА</span><PageTitle>{m?.title ?? 'Раздел'}</PageTitle><p>{m?.description}</p></div><div className="scope-note"><Files size={28}/><h2>Раздел в подготовке</h2><p>Сейчас можно пройти сценарий формирования ГЭК и открыть связанные таблицы людей.</p><Link className="button primary" to="/gek">К формированию ГЭК <ArrowUpRight size={16}/></Link></div></div>; }
const personGroups = [
 {to:'external',title:'Внешние члены ГЭК',copy:'Представители организаций, участвующие в работе комиссий.'},
 {to:'chairmen',title:'Председатели ГЭК',copy:'Председатели комиссий по направлениям подготовки.'},
 {to:'complex',title:'Председатели комплексных ГЭК',copy:'Председатели комиссий, объединяющих несколько программ.'},
];
export function DataHub() { return <div className="page-enter hub-page"><Link className="text-button" to="/">Главная /</Link><div className="hub-welcome"><span className="eyebrow">ОБЩИЕ СПРАВОЧНИКИ</span><PageTitle>Исходные данные</PageTitle><p>Справочники для образовательных программ, комиссий, печатных форм и архива.</p></div><div className="hub-sections"><Link to="/data/people" className="hub-section live"><UsersRound size={25}/><section><span className="eyebrow">01 / УЧАСТНИКИ ГЭК</span><h2>Участники ГЭК</h2><p>Внешние члены, председатели ГЭК и председатели комплексных ГЭК.</p><span className="text-button">Выбрать таблицу <ArrowUpRight size={15}/></span></section></Link><Link to="/data/structure" className="hub-section live"><Building2 size={25}/><section><span className="eyebrow">02 / СТРУКТУРА</span><h2>Структура университета</h2><p>Высшие школы, директора и преподаватели с привязкой к школе.</p><span className="text-button">Открыть справочники <ArrowUpRight size={15}/></span></section></Link><Link to="/data/education" className="hub-section live"><LibraryBig size={25}/><section><span className="eyebrow">03 / ОБРАЗОВАНИЕ</span><h2>Образовательные программы</h2><p>Направления подготовки, образовательные программы и дисциплины.</p><span className="text-button">Выбрать таблицу <ArrowUpRight size={15}/></span></section></Link></div></div>; }
export function PeopleHub() { return <div className="page-enter hub-page"><Link className="text-button" to="/data">Исходные данные /</Link><div className="hub-welcome"><span className="eyebrow">ИСХОДНЫЕ ДАННЫЕ · УЧАСТНИКИ ГЭК</span><PageTitle>Участники ГЭК</PageTitle><p>Выберите таблицу для внешних участников и председателей. Преподаватели находятся в структуре университета.</p></div><div className="people-hub-grid">{personGroups.map((g,i)=><Link className="module-card available" to={`/data/people/${g.to}`} key={g.to}><div className="module-top"><span className="module-icon">{g.to==='external'?<BriefcaseBusiness size={25}/>:g.to==='chairmen'?<UserRoundCheck size={25}/>:<Network size={25}/>}</span><span className="module-number">0{i+1}</span></div><h2>{g.title}</h2><p>{g.copy}</p><footer>Открыть таблицу <ArrowUpRight size={18}/></footer></Link>)}</div><p className="hub-footnote">Один человек не может одновременно находиться в таблице обычных и комплексных председателей.</p></div>; }
export function GekHub() { const {commissions,year}=useGek(); const count=commissions.filter(c=>c.year===year).length; return <div className="page-enter hub-page"><Link className="text-button" to="/">Главная /</Link><div className="hub-welcome"><span className="eyebrow">ГОСУДАРСТВЕННАЯ АТТЕСТАЦИЯ · {year}</span><PageTitle>Формирование ГЭК</PageTitle><p>Подготовьте составы комиссий и сформируйте необходимые документы.</p></div><div className="gek-overview"><section><span className="eyebrow">ТЕКУЩАЯ КАМПАНИЯ</span><h2>{count} комиссий <span>в работе</span></h2><p>Состав, программы и сведения о председателях.</p><Link className="button primary" to="/commissions">Открыть комиссии <ArrowUpRight size={16}/></Link></section><GraduationCap size={110} strokeWidth={.8}/></div><div className="people-hub-grid two"><Link className="module-card available" to="/commissions/new"><Layers3 size={25}/><h2>Создать комиссию</h2><p>Начните с номера и школы, затем заполните карточку.</p><footer>Новая ГЭК <ArrowUpRight size={18}/></footer></Link><Link className="module-card available" to="/gek/documents"><Printer size={25}/><h2>Формирование и печать</h2><p>Составы ГЭК, председатели и секретари. По выбранной школе или по всем школам.</p><footer>Выбрать документ <ArrowUpRight size={18}/></footer></Link></div><Link className="module-card available related-card" to="/data/people"><div className="module-top"><span className="module-icon"><UsersRound size={25}/></span></div><h2>Участники ГЭК</h2><p>Внешние члены, председатели ГЭК и председатели комплексных ГЭК для заполнения комиссий и печати.</p><footer>Перейти к таблицам <ArrowUpRight size={18}/></footer></Link></div>; }
