import { AppSelect } from '../components/AppSelect';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowUpRight, BookOpen, Layers3, GraduationCap, Database, Archive, UsersRound, Building2, LibraryBig, Files, Printer } from 'lucide-react';
import { useStore } from '../store';
import { schools, schoolName, type Commission, csvCell, downloadText } from '../data/model';
import { people } from '../data/seed';
import { DocumentPreview } from '../components/Documents';
import { Modal } from '../components/ui';
const modules = [
 { title:'Разработка и корректировка ООП', description:'Образовательные программы и работа с их содержанием.', to:'/oop', icon:BookOpen, available:false },
 { title:'Формирование аттестационных комиссий', description:'Подготовка составов аттестационных комиссий.', to:'/attestation', icon:Layers3, available:false },
 { title:'Формирование государственных экзаменационных комиссий', description:'Составы ГЭК, карточки председателей и печатные формы.', to:'/gek', icon:GraduationCap, available:true },
 { title:'Исходные данные', description:'Люди, структура университета и образовательные программы.', to:'/data', icon:Database, available:true },
 { title:'Архив', description:'Материалы и документы прошлых кампаний.', to:'/archive', icon:Archive, available:true },
];
export function Home() { return <div className="page-enter hub-page"><div className="hub-welcome"><span className="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО ИПМЭиТ</span><h1>С чего начнём?</h1><p>Выберите направление работы. Всё необходимое — в своём разделе.</p></div><div className="module-grid">{modules.map((m,i) => <Link to={m.to} key={m.to} className={`module-card ${m.available ? 'available' : ''}`}><div className="module-top"><span className="module-icon"><m.icon size={27}/></span><span className="module-number">0{i+1}</span></div><h2>{m.title}</h2><p>{m.description}</p><footer><span>{m.available ? 'Открыть раздел' : 'Обзор раздела'}</span><ArrowUpRight size={18}/></footer></Link>)}</div><p className="hub-footnote">В этом прототипе доступны ГЭК, таблицы людей и архив документов.</p></div>; }
export function Unavailable() { const { module } = useParams(); const m=modules.find(m=>m.to===`/${module}`); return <div className="page-enter hub-page"><Link className="text-button" to="/">← Главная</Link><div className="hub-welcome"><span className="eyebrow">РАЗДЕЛ РАБОЧЕГО ПРОСТРАНСТВА</span><h1>{m?.title ?? 'Раздел'}</h1><p>{m?.description}</p></div><div className="scope-note"><Files size={28}/><h2>Этот раздел пока не входит в демо</h2><p>Сейчас можно пройти сценарий формирования ГЭК и открыть связанные таблицы людей.</p><Link className="button primary" to="/gek">К формированию ГЭК <ArrowUpRight size={16}/></Link></div></div>; }
const personGroups = [
 {to:'external',title:'Внешние члены ГЭК',copy:'Представители организаций, участвующие в работе комиссий.'},
 {to:'chairmen',title:'Председатели ГЭК',copy:'Председатели комиссий по направлениям подготовки.'},
 {to:'complex',title:'Председатели комплексных ГЭК',copy:'Председатели комиссий, объединяющих несколько программ.'},
];
export function DataHub() { return <div className="page-enter hub-page"><Link className="text-button" to="/">Главная /</Link><div className="hub-welcome"><span className="eyebrow">ОБЩИЕ СПРАВОЧНИКИ</span><h1>Исходные данные</h1><p>Информация, на которой строится работа с программами и комиссиями.</p></div><div className="hub-sections"><Link to="/data/people" className="hub-section live"><UsersRound size={25}/><section><span className="eyebrow">01 / ЛЮДИ</span><h2>Люди</h2><p>Сотрудники, внешние участники и председатели — в одной группе.</p><span className="text-button">Выбрать таблицу <ArrowUpRight size={15}/></span></section></Link><div className="hub-section"><Building2 size={25}/><section><span className="eyebrow">02 / СТРУКТУРА</span><h2>Структура университета</h2><p>Высшие школы, подразделения и директора.</p><small>Позже · у директора: ФИО, высшая школа и должность, включая и.о.</small></section></div><div className="hub-section"><LibraryBig size={25}/><section><span className="eyebrow">03 / ОБРАЗОВАНИЕ</span><h2>Образовательные программы</h2><p>Направления, профили и дисциплины.</p><small>Пока обозначена только структура раздела.</small></section></div></div></div>; }
export function PeopleHub() { return <div className="page-enter hub-page"><Link className="text-button" to="/data">Исходные данные /</Link><div className="hub-welcome"><span className="eyebrow">ИСХОДНЫЕ ДАННЫЕ · ЛЮДИ</span><h1>Люди</h1><p>Выберите таблицу по задаче. Один человек может участвовать в разных ролях.</p></div><div className="people-hub-grid">{personGroups.map((g,i)=><Link className="module-card available" to={`/data/people/${g.to}`} key={g.to}><div className="module-top"><span className="module-icon"><UsersRound size={25}/></span><span className="module-number">0{i+1}</span></div><h2>{g.title}</h2><p>{g.copy}</p><footer>Открыть таблицу <ArrowUpRight size={18}/></footer></Link>)}</div><p className="hub-footnote">Внутренние сотрудники также могут быть председателями. Место работы и роль в комиссии — разные сведения.</p></div>; }
export function GekHub() { const {commissions,year}=useStore(); const count=commissions.filter(c=>c.year===year).length; return <div className="page-enter hub-page"><Link className="text-button" to="/">Главная /</Link><div className="hub-welcome"><span className="eyebrow">ГОСУДАРСТВЕННАЯ АТТЕСТАЦИЯ · {year}</span><h1>Формирование ГЭК</h1><p>Подготовьте составы комиссий и сформируйте необходимые документы.</p></div><div className="gek-overview"><section><span className="eyebrow">ТЕКУЩАЯ КАМПАНИЯ</span><h2>{count} комиссий <span>в работе</span></h2><p>Состав, программы и сведения о председателях.</p><Link className="button primary" to="/commissions">Открыть комиссии <ArrowUpRight size={16}/></Link></section><GraduationCap size={110} strokeWidth={.8}/></div><div className="people-hub-grid two"><Link className="module-card available" to="/commissions/new"><Layers3 size={25}/><h2>Создать комиссию</h2><p>Начните с номера и школы, затем заполните карточку.</p><footer>Новая ГЭК <ArrowUpRight size={18}/></footer></Link><Link className="module-card available" to="/gek/documents"><Printer size={25}/><h2>Формирование и печать</h2><p>Составы ГЭК, председатели и секретари. По школе или все сразу.</p><footer>Выбрать документ <ArrowUpRight size={18}/></footer></Link></div><Link className="hub-related" to="/data/people"><UsersRound size={19}/><span>Нужны исходные сведения о людях?</span><strong>Перейти к таблицам</strong><ArrowUpRight size={16}/></Link></div>; }
export function GekDocuments() {
 const {commissions,year}=useStore(); const [school,setSchool]=useState(''); const [preview,setPreview]=useState<{kind:string;rows:Commission[]}|null>(null);
 const rows=commissions.filter(c=>c.year===year); const selected=rows.filter(c=>c.school===school);
 return <div className="page-enter hub-page"><Link className="text-button" to="/gek">Формирование ГЭК /</Link><div className="hub-welcome"><span className="eyebrow">ДОКУМЕНТЫ · {year}</span><h1>Формирование и печать</h1><p>Все печатные формы ГЭК в одном месте.</p></div><label className="document-school">Высшая школа<AppSelect value={school} onChange={e=>setSchool(e.target.value)}><option value="">Выберите высшую школу</option>{schools.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</AppSelect><small>Выбор школы применяется к кнопкам «По выбранной школе».</small></label><div className="print-actions">{[['table','Составы ГЭК','Председатель, участники, секретарь и программы.'],['chairmen','Состав председателей ГЭК','Председатели обычных и комплексных комиссий.'],['secretaries','Секретари ГЭК','Секретари с указанием комиссии и высшей школы.']].map(([kind,title,copy])=><section key={kind}><span className="module-icon"><Printer size={23}/></span><div><h2>{title}</h2><p>{copy}</p><div className="button-row"><button className="button primary" disabled={!school||!selected.length} onClick={()=>setPreview({kind,rows:selected})}>По выбранной школе</button><button className="button secondary" disabled={!rows.length} onClick={()=>setPreview({kind,rows})}>По всем школам</button></div></div></section>)}</div>{school && !selected.length && <p className="info-note">Для этой школы в {year} году нет комиссий.</p>}{preview && (preview.kind==='table'?<DocumentPreview rows={preview.rows} onClose={()=>setPreview(null)}/>:<RoleDocument kind={preview.kind} rows={preview.rows} onClose={()=>setPreview(null)}/>)}</div>;
}
function RoleDocument({kind,rows,onClose}:{kind:string;rows:Commission[];onClose:()=>void}) {
 const title=kind==='chairmen'?'Состав председателей ГЭК':'Секретари ГЭК';
 const data=rows.map(c=>{const p=people.find(p=>p.id===(kind==='chairmen'?c.chairmanId:c.secretaryId));return [c.number,schoolName(c.school),c.type==='complex'?'Комплексная':'По направлению',p?.name??'—',p?.organization??'—',p?.position??'—'];});
 const headings=['№ ГЭК','Высшая школа','Тип комиссии','ФИО','Организация','Должность'];
 return <Modal title={title} onClose={onClose} wide subtitle="Предпросмотр сохранённых сведений" footer={<><button className="button secondary" onClick={()=>downloadText('\uFEFF'+[headings,...data].map(r=>r.map(csvCell).join(';')).join('\r\n'),`${title}.csv`)}>Скачать CSV</button><button className="button primary" onClick={()=>window.print()}>Печать / PDF</button></>}><div className="document-paper landscape"><div className="document-header"><h2>{title}</h2><p>{rows[0]?.year} год · {new Set(rows.map(c=>c.school)).size===1?schoolName(rows[0]?.school):'Все высшие школы'}</p></div><table className="document-table"><thead><tr>{headings.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.map((r,i)=><tr key={rows[i].id}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table><p className="document-demo">Демонстрационный образец · вымышленные данные</p></div></Modal>;
}
