import { useState, type FormEvent } from 'react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, LockKeyhole, Check, PanelsTopLeft, Layers3 } from 'lucide-react';
import { Brand, Field } from '../components/ui';
import { useStore } from '../store';
export function Login() {
 const { authenticated, login } = useStore(); const navigate = useNavigate(); const location = useLocation();
 const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [error, setError] = useState('');
 if (authenticated) return <Navigate to="/" replace/>;
 const submit = (e: FormEvent) => { e.preventDefault(); if (username.trim() !== 'admin' || password !== '12345678') { setError('Для демо используйте логин admin и пароль 12345678.'); return; } login(); navigate('/', { replace: true }); };
 return <main className="login-page"><section className="login-editorial"><Brand/><div className="editorial-copy"><span className="editorial-label"><span/> ОБРАЗОВАТЕЛЬНАЯ СРЕДА</span><h1>Большая работа.<br/>Продумана<br/><em>до деталей.</em></h1><p>Программы, комиссии и документы.<br/>Единое пространство для вашей работы.</p></div><div className="editorial-art" aria-hidden="true"><div className="arch arch-one"/><div className="arch arch-two"/><div className="arch arch-three"/><div className="art-card"><span className="art-card-icon"><Layers3 size={22}/></span><span><strong>Всё на своих местах</strong><small>От состава комиссии до документа</small></span><span className="art-check"><Check size={14}/></span></div></div><footer><span>Санкт-Петербургский политехнический<br/>университет Петра Великого</span><span>2026</span></footer></section><section className="login-main"><span className="login-topline"><PanelsTopLeft size={15}/> Рабочее пространство ИПМЭиТ</span><div className="login-form-wrap"><span className="login-form-icon"><LockKeyhole size={23}/></span><h2>С возвращением</h2><p className="login-description">Войдите, чтобы продолжить работу<br/>с экзаменационными комиссиями.</p><form onSubmit={submit}><Field label="Логин"><input name="username" autoComplete="username" placeholder="Введите ваш логин" value={username} onChange={e => { setUsername(e.target.value); setError(''); }} required/></Field><Field label="Пароль"><span className="password-input"><input name="password" autoComplete="current-password" type={visible ? 'text' : 'password'} placeholder="Введите пароль" value={password} onChange={e => { setPassword(e.target.value); setError(''); }} required/><button type="button" className="icon-button" aria-label={visible ? 'Скрыть пароль' : 'Показать пароль'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={18}/> : <Eye size={18}/>}</button></span></Field>{error && <p className="form-error" role="alert">{error}</p>}<button type="submit" className="button primary login-submit">Войти в рабочее пространство <ArrowRight size={18}/></button></form><div className="demo-access"><div><span className="demo-dot"/><strong>Демонстрационный доступ</strong></div><p>Можно спокойно изучить интерфейс.<br/>Все данные в этой версии вымышлены.</p><button onClick={() => { setUsername('admin'); setPassword('12345678'); setError(''); }}>Заполнить данные для входа <ArrowRight size={14}/></button></div></div><footer className="login-footer">ИПМЭиТ <span>·</span> Государственные экзаменационные комиссии</footer></section></main>;
}

