import { useState, type FormEvent } from 'react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, LockKeyhole, Check, PanelsTopLeft, Layers3 } from 'lucide-react';
import { Brand, Field } from '../components/ui';
import { useStore } from '../store';
export function Login() {
 const { authenticated, login, authLoading } = useStore(); const navigate = useNavigate(); const location = useLocation();
 const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [error, setError] = useState('');

 const [pending, setPending] = useState(false);
 const submit = async (e: FormEvent) => { e.preventDefault(); if(pending)return; setPending(true); setError(''); try { await login(username.trim(),password); navigate('/', { replace: true }); } catch(error) { setError((error as Error).message); } finally { setPending(false); } };
 if (authenticated) return <Navigate to="/" replace/>;
 return <main className="login-page"><section className="login-editorial"><Brand/><div className="editorial-copy"><span className="editorial-label"><span/> ОБРАЗОВАТЕЛЬНАЯ СРЕДА</span><h1 className="system-login-title">Автоматизированная система поддержки образовательного процесса ИПМЭиТ</h1><p>Образовательные программы, комиссии,<br/>справочники и архив документов.</p></div><div className="editorial-art" aria-hidden="true"><div className="arch arch-one"/><div className="arch arch-two"/><div className="arch arch-three"/><div className="art-card"><span className="art-card-icon"><Layers3 size={22}/></span><span><strong>Образовательный процесс</strong><small>Программы, комиссии и документы</small></span><span className="art-check"><Check size={14}/></span></div></div><footer><span>Санкт-Петербургский политехнический<br/>университет Петра Великого</span><span>2026</span></footer></section><section className="login-main"><span className="login-topline"><PanelsTopLeft size={15}/> ИПМЭиТ</span><div className="login-form-wrap"><span className="login-form-icon"><LockKeyhole size={23}/></span><h2>Вход в систему</h2><p className="login-description">Введите логин и пароль для доступа к системе.</p><form onSubmit={submit}><Field label="Логин"><input name="username" autoComplete="username" placeholder="Введите ваш логин" value={username} onChange={e => { setUsername(e.target.value); setError(''); }} required/></Field><Field label="Пароль"><span className="password-input"><input name="password" autoComplete="current-password" type={visible ? 'text' : 'password'} placeholder="Введите пароль" value={password} onChange={e => { setPassword(e.target.value); setError(''); }} required/><button type="button" className="icon-button" aria-label={visible ? 'Скрыть пароль' : 'Показать пароль'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={18}/> : <Eye size={18}/>}</button></span></Field>{error && <p className="form-error" role="alert">{error}</p>}<button type="submit" disabled={pending || authLoading} className="button primary login-submit">{pending ? 'Вход…' : 'Войти в систему'} <ArrowRight size={18}/></button></form></div><footer className="login-footer">Автоматизированная система поддержки образовательного процесса ИПМЭиТ</footer></section></main>;
}

