import { PageTitle } from '../components/PageTitle';
import { AppSelect } from '../components/AppSelect';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, UsersRound, ArrowUpRight, Building2, GraduationCap } from 'lucide-react';
import { people } from '../data/seed';
import { useStore } from '../store';
import { Avatar, Empty, Modal } from '../components/ui';
import type { Person } from '../data/model';
export function People() {
 const { commissions } = useStore(); const [query, setQuery] = useState(''); const [kind, setKind] = useState('all'); const [person, setPerson] = useState<Person | null>(null);
 const filtered = people.filter(p => (kind === 'all' || kind === p.kind) && `${p.name} ${p.organization}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));
 return <div className="page-enter"><div className="page-heading"><div><div className="heading-eyebrow"><UsersRound size={16}/> СПРАВОЧНИК</div><PageTitle>Участники и председатели</PageTitle><p>Сотрудники университета и представители внешних организаций.</p></div></div><div className="table-toolbar directory-toolbar"><div className="search-field"><Search size={17}/><input aria-label="Поиск участников" placeholder="Имя или организация" value={query} onChange={e => setQuery(e.target.value)}/></div><AppSelect className="directory-select" aria-label="Тип участника" value={kind} onChange={e => setKind(e.target.value)}><option value="all">Все участники</option><option value="internal">Сотрудники университета</option><option value="external">Внешние участники</option></AppSelect><span className="muted">{filtered.length} записей</span></div><div className="directory-grid">{filtered.map(p => <button key={p.id} className="directory-card" onClick={() => setPerson(p)}><div><Avatar person={p}/><ArrowUpRight size={17}/></div><h3>{p.name}</h3><p>{p.position}</p><span><Building2 size={14}/>{p.organization}</span><footer>{p.kind === 'external' ? 'Внешний участник' : 'Сотрудник университета'}</footer></button>)}</div>{!filtered.length && <Empty title="Участник не найден">Измените запрос или тип участника.</Empty>}{person && <Modal title={person.name} subtitle={person.kind === 'external' ? 'Внешний участник' : 'Сотрудник университета'} onClose={() => setPerson(null)}><div className="directory-detail"><Avatar person={person}/><h3>{person.position}</h3><p><Building2 size={16}/>{person.organization}</p><p><GraduationCap size={16}/>{person.degree}</p><h4>Участие в комиссиях</h4>{commissions.filter(c => [c.chairmanId, c.secretaryId, ...c.internalIds, ...c.externalIds].includes(person.id)).map(c => <Link key={c.id} to={`/commissions/${c.id}`} onClick={() => setPerson(null)}>ГЭК № {c.number} · {c.year}<span>{c.chairmanId === person.id ? 'Председатель' : c.secretaryId === person.id ? 'Секретарь' : 'Участник'}<ArrowUpRight size={14}/></span></Link>)}<small>Вымышленные сведения для демонстрации интерфейса.</small></div></Modal>}</div>;
}
