import {useState} from 'react';
import type {Person} from '../data/model';
import {schools} from '../data/model';
import {Field,Modal} from './ui';
import {AppSelect} from './AppSelect';
import type {Entry} from '../pages/PeopleTable';
export function AddPersonEntry({category,people,entries,onAdd,onClose}:{category:string;people:Person[];entries:Entry[];onAdd:(entry:Entry)=>boolean;onClose:()=>void}){
 const external=category==='external';const [personId,setPersonId]=useState('');const [sphere,setSphere]=useState('');const [school,setSchool]=useState('');const [values,setValues]=useState({name:'',organization:'',position:'',degree:'',rank:''});const [error,setError]=useState('');
 const submit=()=>{let person=people.find(p=>p.id===personId);if(external){if(!values.name.trim()){setError('Укажите ФИО');return;}person={id:crypto.randomUUID(),name:values.name.trim(),organization:values.organization.trim(),position:values.position.trim(),degree:values.degree.trim()||'—',rank:values.rank.trim()||'—',kind:'external',color:'sage',initials:values.name.trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('')};}else{if(!person||!sphere||(category==='chairmen'&&!school)){setError('Выберите человека, сферу деятельности и высшую школу, если она требуется.');return;}if(entries.some(e=>e.personId===person!.id&&e.sphere===sphere&&(category==='complex'||e.schoolIds.includes(school)))){setError('Такая запись уже есть в таблице');return;}}
 const row:Entry={id:crypto.randomUUID(),personId:person!.id,person:person!,sphere:(sphere||'Бизнес') as Entry['sphere'],schoolIds:school?[school]:[],values:{}};if(!onAdd(row))setError('Не удалось сохранить запись. Проверьте доступность хранилища браузера.');};
 return <Modal title={external?'Добавить внешнего члена ГЭК':category==='complex'?'Добавить председателя комплексной ГЭК':'Добавить председателя ГЭК'} subtitle={external?'Сведения об участнике из внешней организации':'После добавления откроется профессиональная карточка'} onClose={onClose} footer={<><button className="button secondary" onClick={onClose}>Отмена</button><button className="button primary" form="add-person-entry" type="submit">{external?'Добавить':'Добавить и заполнить'}</button></>}><form id="add-person-entry" onSubmit={e=>{e.preventDefault();submit();}}>{external?Object.entries({name:'ФИО',organization:'Организация',position:'Должность',degree:'Учёная степень',rank:'Учёное звание'}).map(([key,label])=><Field key={key} label={label} required={key==='name'}><input aria-label={label} required={key==='name'} value={values[key as keyof typeof values]} onChange={e=>{setValues({...values,[key]:e.target.value});setError('');}}/></Field>):<><Field label="Председатель" required><AppSelect aria-label="Председатель" required value={personId} onChange={e=>{setPersonId(e.target.value);setError('');}}><option value="">Выберите человека</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</AppSelect></Field><Field label="Сфера деятельности" required><AppSelect aria-label="Сфера деятельности" required value={sphere} onChange={e=>{setSphere(e.target.value);setError('');}}><option value="">Выберите сферу</option><option>Образование</option><option>Бизнес</option></AppSelect></Field>{category==='chairmen'?<Field label="Высшая школа" required><AppSelect aria-label="Высшая школа" required value={school} onChange={e=>{setSchool(e.target.value);setError('');}}><option value="">Выберите высшую школу</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</AppSelect></Field>:<p className="field-hint">Высшие школы можно выбрать следующим шагом в карточке комплексной ГЭК.</p>}</>}{error&&<p className="form-error" role="alert">{error}</p>}</form></Modal>;
}
