import { PageTitle } from './PageTitle';
import { AppSelect } from './AppSelect';
import { useEffect, useState, type ReactNode } from 'react';
import { useBlocker } from 'react-router-dom';
import { ArrowLeft, BookOpen, Building2, Check, FileText, GraduationCap, Save, UserRound } from 'lucide-react';
import type { Entry } from '../pages/PeopleTable';
import { type Person, schools } from '../data/model';
import { Avatar, Confirm, Field, SectionHeading } from './ui';
export function ChairmanCard({entry,person,complex,onChange,onSave,onBack}:{entry:Entry;person:Person;complex:boolean;onChange:(entry:Entry)=>void;onSave:()=>boolean|undefined;onBack:()=>void}) {
 const [baseline,setBaseline]=useState(()=>JSON.stringify(entry)); const dirty=baseline!==JSON.stringify(entry);
 const blocker=useBlocker(({currentLocation,nextLocation})=>dirty&&(currentLocation.pathname!==nextLocation.pathname||currentLocation.search!==nextLocation.search));
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 const save=()=>{if(onSave())setBaseline(JSON.stringify(entry));};
 const input=(key:string,label:string,placeholder='')=><Field key={key} label={label}><input aria-label={label} value={entry.values[key]??''} placeholder={placeholder} onChange={e=>onChange({...entry,values:{...entry.values,[key]:e.target.value}})}/></Field>;
 const section=(title:string,description:string,icon:ReactNode,children:ReactNode)=><section className="form-section"><header><span>{icon}</span><div><h3>{title}</h3><p>{description}</p></div></header>{children}</section>;
 const extra=entry.sphere==='Образование'?[['publications','Публикации по программе'],['lectures','Лекции по программе']]:[['type_activity','Вид деятельности'],['career_activity','Род профессиональной деятельности кандидата'],['candidate_is','Кандидат является']];
 return <div className="page-enter detail-page chairman-card"><div className="breadcrumb"><button onClick={onBack}><ArrowLeft size={14}/> {complex?'Председатели комплексных ГЭК':'Председатели ГЭК'}</button><span>/ Карточка</span></div><div className="page-heading detail-heading"><div><div className="heading-eyebrow">ИСХОДНЫЕ ДАННЫЕ · ЛЮДИ</div><PageTitle>Карточка председателя</PageTitle><p>{complex?'Комплексная ГЭК':'ГЭК по направлению'} · {entry.sphere}</p></div><button className="button primary" disabled={!dirty} onClick={save}><Check size={17}/> Сохранить</button></div><div className="detail-grid"><div className="detail-primary"><SectionHeading eyebrow="СВЕДЕНИЯ О ПРЕДСЕДАТЕЛЕ" title="Профессиональная карточка" description="Образование, научная квалификация и профессиональная деятельность."/><div className="profile-person"><Avatar person={person}/><div><h3>{person.name}</h3><p>{person.position} · {person.organization}</p></div><span className="subtle-pill">{entry.sphere}</span></div><div className="profile-form">
 {section(complex?'Высшие школы':'Высшая школа','Принадлежность карточки председателя',<Building2 size={19}/>,complex?<div className="school-checks">{schools.map(s=><label key={s.id}><input type="checkbox" checked={entry.schoolIds.includes(s.id)} onChange={e=>onChange({...entry,schoolIds:e.target.checked?[...entry.schoolIds,s.id]:entry.schoolIds.filter(id=>id!==s.id)})}/>{s.name}</label>)}</div>:<Field label="Высшая школа"><AppSelect aria-label="Высшая школа" value={entry.schoolIds[0]??''} onChange={e=>onChange({...entry,schoolIds:[e.target.value]})}>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</AppSelect></Field>)}
 {section('Образование','Сведения в соответствии с документом об образовании',<GraduationCap size={19}/>,<>{input('university','Учебное заведение','Полное наименование университета')}{input('education','Наименование образования')}{input('qualification','Специальность и квалификация','В соответствии с дипломом')}</>)}
 {section('Учёная степень',person.degree,<BookOpen size={18}/>,<div className="form-grid three">{input('diplomaSeries','Серия диплома о степени')}{input('diplomaNumber','Номер диплома')}{input('diplomaDate','Дата диплома')}</div>)}
 {section('Учёное звание',person.rank,<FileText size={18}/>,<><div className="form-grid">{input('department','Кафедра')}{input('speciality','Научная специальность')}</div><div className="form-grid three">{input('certificateSeries','Серия аттестата')}{input('certificateNumber','Номер аттестата')}{input('certificateDate','Дата аттестата')}</div>{input('honoraryTitle','Почётное звание','При наличии')}</>)}
 {section(entry.sphere==='Образование'?'Научная и преподавательская деятельность':'Профессиональная деятельность',`Поля для сферы «${entry.sphere}»`,<UserRound size={18}/>,extra.map(([key,label])=><Field key={key} label={label}><textarea aria-label={label} rows={4} value={entry.values[key]??''} onChange={e=>onChange({...entry,values:{...entry.values,[key]:e.target.value}})}/></Field>))}
 </div></div><aside className="detail-aside"><div className="completion-card"><span className="eyebrow">О КАРТОЧКЕ</span><h3>{entry.sphere}</h3><p>{entry.sphere==='Образование'?'Публикации и лекции по образовательной программе.':'Вид деятельности, профессиональные обязанности и сведения о кандидате.'}</p></div><div className="detail-summary"><h3>Сведения из справочника</h3><dl><div><dt>Председатель</dt><dd>{person.name}</dd></div><div><dt>Тип</dt><dd>{complex?'Комплексная ГЭК':'ГЭК по направлению'}</dd></div><div><dt>Место работы</dt><dd>{person.organization}</dd></div></dl></div></aside></div>{dirty&&<div className="save-bar"><span><span className="unsaved-dot"/>Есть несохранённые изменения</span><div><button className="button secondary" onClick={()=>onChange(JSON.parse(baseline))}>Отменить изменения</button><button className="button primary" onClick={save}><Save size={16}/> Сохранить изменения</button></div></div>}{blocker.state==='blocked'&&<Confirm title="Изменения ещё не сохранены" confirmLabel="Уйти без сохранения" onClose={()=>blocker.reset()} onConfirm={()=>blocker.proceed()}>Можно остаться и сохранить карточку или уйти без сохранения изменений.</Confirm>}</div>;
}
