import { useState } from 'react';
import { Download, Printer, FileText, CheckCircle2, Info, ArrowUpRight } from 'lucide-react';
import { Modal } from './ui';
import { type Commission, schoolName, downloadText, makeCsv, isReady, completeness } from '../data/model';
import { people, programs } from '../data/seed';
const personName = (id: string) => people.find(p => p.id === id)?.name ?? 'Не указан';
export function DocumentPreview({ rows, onClose, mode = 'table' }: { rows: Commission[]; onClose: () => void; mode?: 'table' | 'card' }) {
 const c = rows[0]; const chairman = people.find(p => p.id === c?.chairmanId); const missing = rows.filter(c => !isReady(c)).length;
 return <Modal title={mode === 'table' ? 'Таблица государственных экзаменационных комиссий' : `Карточка председателя · ГЭК № ${c?.number}`} subtitle="Предпросмотр на основе сохранённых сведений" onClose={onClose} wide footer={<><span className="muted preview-caption">Демо · не является официальным документом</span><button className="button secondary" onClick={() => downloadText(makeCsv(rows, people, programs), 'Состав ГЭК.csv')}><Download size={16}/> Скачать CSV</button><button className="button primary" onClick={() => window.print()}><Printer size={16}/> Печать / PDF</button></>}><div className="print-note"><Info size={17}/><span>{missing ? `У ${missing} комиссий есть незаполненные сведения. В документе они отмечены прочерком.` : 'Сведения заполнены. Проверьте документ перед печатью.'} PDF можно сохранить через диалог печати браузера.</span></div><div className={`document-paper ${mode === 'table' ? 'landscape' : ''}`}><div className="document-header"><span>САНКТ-ПЕТЕРБУРГСКИЙ ПОЛИТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ПЕТРА ВЕЛИКОГО</span><p>Институт промышленного менеджмента, экономики и торговли</p><h2>{mode === 'table' ? 'Состав государственных экзаменационных комиссий' : 'Сведения о председателе государственной экзаменационной комиссии'}</h2><p>на {c?.year ?? '2026'} год</p></div>{mode === 'table' ? <table className="document-table"><thead><tr><th>№ ГЭК</th><th>Высшая школа / программа</th><th>Председатель</th><th>Состав комиссии</th><th>Секретарь</th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td>{r.number}</td><td><strong>{schoolName(r.school)}</strong>{r.programIds.map(id => { const p = programs.find(p => p.id === id); return <p key={id}>{p?.code} — {p?.name}</p>; })}{!r.programIds.length && <p>Программы не указаны</p>}</td><td>{personName(r.chairmanId)}<p>{people.find(p => p.id === r.chairmanId)?.position}</p></td><td>{[...r.internalIds, ...r.externalIds].map(id => <p key={id}>{personName(id)}</p>)}{!r.internalIds.length && !r.externalIds.length && '—'}</td><td>{personName(r.secretaryId)}</td></tr>)}</tbody></table> : c && <table className="document-table profile-document"><tbody>{[
 ['ГЭК', `№ ${c.number} · ${schoolName(c.school)}`], ['Председатель', personName(c.chairmanId)], ['Организация', chairman?.organization], ['Должность', chairman?.position], ['Учёная степень', chairman?.degree], ['Учёное звание', chairman?.rank], ['Образовательные программы', c.programIds.map(id => { const p = programs.find(p => p.id === id); return `${p?.code} ${p?.name}`; }).join('\n')], ['Образование', c.profile.university], ['Направление подготовки', c.profile.educationName], ['Квалификация', c.profile.qualification], ['Диплом о степени', `${c.profile.diplomaSeries} ${c.profile.diplomaNumber} ${c.profile.diplomaDate}`.trim()], ['Кафедра', c.profile.department], ['Научная специальность', c.profile.speciality], ['Аттестат о звании', `${c.profile.certificateSeries} ${c.profile.certificateNumber} ${c.profile.certificateDate}`.trim()], ['Почётное звание', c.profile.honoraryTitle], ['Публикации', c.profile.publications], ['Лекции', c.profile.lectures], ['Сфера деятельности', c.profile.activity], ['Опыт работы', c.profile.experience],
 ].map(([label, value]) => <tr key={label}><th>{label}</th><td>{value || '—'}</td></tr>)}</tbody></table>}<div className="document-signature"><span>Ответственный за формирование __________________</span><span>Дата __________________</span></div><div className="document-demo">Демонстрационный образец · вымышленные данные</div></div></Modal>;
}
export function DocumentCards({ commission, dirty, onSave }: { commission: Commission; dirty: boolean; onSave: () => void }) {
 const [preview, setPreview] = useState<'table' | 'card' | null>(null); const checks = completeness(commission);
 return <><div className="section-heading"><div><span className="eyebrow">ФОРМИРОВАНИЕ ДОКУМЕНТОВ</span><h2>Всё готово к следующему шагу</h2><p>Проверьте заполнение и сформируйте документ из карточки.</p></div></div>{dirty && <div className="info-note"><Info size={18}/><p>Перед формированием документа сохраните изменения.</p><button className="text-button" onClick={onSave}>Сохранить</button></div>}<div className="document-cards">{[['table', 'Состав комиссии', 'Председатель, секретарь, участники и образовательные программы.'], ['card', 'Карточка председателя', 'Образование, степень, звание и профессиональная деятельность.']].map(([mode, title, copy]) => <button className="document-card" key={mode} disabled={dirty} onClick={() => setPreview(mode as 'table' | 'card')}><div className="document-thumbnail"><FileText size={28}/><div/><div/><div/></div><section><h3>{title}</h3><p>{copy}</p><span>Открыть предпросмотр <ArrowUpRight size={15}/></span></section></button>)}</div><div className="readiness-panel"><h3>Проверка заполнения</h3><p>Помогает найти пропуски в демо. Не заменяет проверку и утверждение состава.</p>{checks.map((check, i) => <div className={check.done ? 'done' : ''} key={i}><CheckCircle2 size={17}/><span>{check.label}</span><small>{check.done ? 'Заполнено' : 'Нужно дополнить'}</small></div>)}</div>{preview && <DocumentPreview rows={[commission]} mode={preview} onClose={() => setPreview(null)}/>}</>;
}
