import { AppSelect } from './AppSelect';
import { Navigation } from './Navigation';
import { useState } from 'react';
import { NavLink, Navigate, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { PanelsTopLeft, UsersRound, CircleHelp, ChevronDown, LogOut, PanelLeftClose, Menu, CheckCircle2, ArrowUpRight, GraduationCap } from 'lucide-react';
import { Brand, Help } from './ui';
import { useStore } from '../store';
export function Layout() {
 const { authenticated, logout, toast, year, setYear } = useStore(); const [mobileOpen, setMobileOpen] = useState(false); const [help, setHelp] = useState(false); const location = useLocation(); const navigate = useNavigate();
 if (!authenticated) return <Navigate to="/login" state={{ from: location.pathname + location.search }} replace/>;
 return <div className="workspace">{mobileOpen && <button className="sidebar-scrim" aria-label="Закрыть навигацию" onClick={() => setMobileOpen(false)}/>}<aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}><div className="sidebar-brand"><Brand/><button className="icon-button mobile-only" aria-label="Скрыть меню" onClick={() => setMobileOpen(false)}><PanelLeftClose size={19}/></button></div><div className="workspace-selector"><span className="workspace-logo">И</span><div><strong>ИПМЭиТ</strong><span>Образовательная деятельность</span></div><GraduationCap size={18}/></div><div className="nav-caption">РАБОЧЕЕ ПРОСТРАНСТВО</div><Navigation onNavigate={() => setMobileOpen(false)}/><div className="sidebar-season"><span className="season-symbol">✳</span><div><span>Кампания ГЭК</span><strong>{year}/{Number(year) + 1}</strong></div><span className="season-live"/></div><div className="sidebar-bottom"><button className="nav-item help-button" onClick={() => setHelp(true)}><CircleHelp size={18}/><span>Как работать с ГЭК</span><ArrowUpRight size={15}/></button><div className="user-panel"><span className="avatar user-avatar">АК</span><div><strong>Администратор</strong><span>Демонстрационный доступ</span></div><button className="icon-button" title="Выйти" aria-label="Выйти из системы" onClick={() => navigate('/logout')}><LogOut size={17}/></button></div></div></aside><div className="workspace-body"><header className="topbar"><div className="topbar-location"><button className="icon-button mobile-only" aria-label="Открыть меню" onClick={() => setMobileOpen(true)}><Menu size={21}/></button><span>Образовательная деятельность</span><span className="topbar-slash">/</span><strong>{location.pathname.startsWith('/data') ? 'Исходные данные' : location.pathname === '/' ? 'Рабочее пространство' : 'Государственная аттестация'}</strong></div><div className="topbar-actions"><span className="demo-tag"><span/>Демо</span><label className="year-control"><AppSelect aria-label="Год кампании" value={year} onChange={e => setYear(e.target.value)}><option value="2025">2025/2026</option><option value="2026">2026/2027</option></AppSelect><ChevronDown size={14}/></label></div></header><main id="main-content" className="main-content"><Outlet/></main><footer className="workspace-footer"><span>ИПМЭиТ · Государственные экзаменационные комиссии</span><span>Демонстрационная версия</span></footer></div>{help && <Help onClose={() => setHelp(false)}/ >}{toast && <div className="toast" role="status"><CheckCircle2 size={19}/><span>{toast}</span></div>}</div>;
}
export function Logout() { const { logout } = useStore(); const navigate = useNavigate(); return <div className="logout-card"><LogOut size={28}/><h1>Выйти из рабочего пространства?</h1><p>Сохранённые демоданные останутся в этом браузере.</p><div className="button-row"><button className="button secondary" onClick={() => navigate('/commissions')}>Остаться</button><button className="button primary" onClick={() => { logout(); navigate('/login', { replace: true }); }}>Выйти</button></div></div>; }

