import { useEffect, useState } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { ChevronDown, House, Layers3, GraduationCap, Database, Archive, BookOpen } from 'lucide-react';
export function Navigation({ onNavigate }: { onNavigate: () => void }) {
 const { pathname } = useLocation(); const isGek = pathname.startsWith('/gek') || pathname.startsWith('/commissions'); const isData = pathname.startsWith('/data');
 const [open, setOpen] = useState({ oop: pathname.startsWith('/oop'), attestation: pathname.startsWith('/attestation'), gek: isGek, data: isData, people: pathname.includes('/people')||pathname.endsWith('/teachers'), structure:pathname.includes('/structure')||pathname.endsWith('/schools'), education:pathname.includes('/education')||['/directions','/programs','/disciplines'].some(x=>pathname.endsWith(x)) });
 useEffect(() => { setOpen(o => ({ ...o, ...(pathname.startsWith('/oop') ? {oop:true} : {}), ...(pathname.startsWith('/attestation') ? { attestation: true } : {}), ...(isGek ? { gek: true } : {}), ...(isData ? { data: true } : {}), ...(pathname.includes('/people')||pathname.endsWith('/teachers') ? { people: true } : {}), ...(pathname.includes('/structure')||pathname.endsWith('/schools')?{structure:true}:{}), ...(pathname.includes('/education')||['/directions','/programs','/disciplines'].some(x=>pathname.endsWith(x))?{education:true}:{}) })); }, [pathname, isGek, isData]);
 const [attOpen, setAttOpen] = useState<Record<string, boolean>>({spo: pathname.startsWith('/attestation/spo'), ac: pathname.startsWith('/attestation/ac'), ppa: pathname.startsWith('/attestation/ppa')});
 useEffect(() => { const kind = pathname.split('/')[2]; if (pathname.startsWith('/attestation/') && ['spo','ac','ppa'].includes(kind)) setAttOpen(o => ({...o,[kind]:true})); }, [pathname]);
 const link = (to: string, text: string, end = true) => <NavLink to={to} end={end} onClick={onNavigate} className={({ isActive }) => `tree-link ${isActive ? 'active' : ''}`}>{text}</NavLink>;
 return <nav className="navigation-tree" aria-label="Основная навигация">
 
 <div className="tree-heading"><BookOpen size={17}/>{link('/oop','Разработка ООП')}<button aria-label="Подразделы ООП" aria-expanded={open.oop} onClick={() => setOpen(o => ({...o,oop:!o.oop}))}><ChevronDown size={14}/></button></div>
 {open.oop && <div className="tree-branch">{link('/oop/formation','Формирование ООП')}{link('/oop/print','Печать')}{link('/oop/data','Ввод исходных данных',false)}{link('/oop/status','Проверка статуса ООП')}</div>}
 <div className="tree-heading"><Layers3 size={17}/>{link('/attestation','Аттестационные комиссии')}<button aria-label="Подразделы аттестационных комиссий" aria-expanded={open.attestation} onClick={() => setOpen(o => ({...o,attestation:!o.attestation}))}><ChevronDown size={14}/></button></div>
 {open.attestation && <div className="tree-branch">{[['spo','Комиссии СПО'],['ac','Аттестационные комиссии'],['ppa','Комиссии ППА']].map(([kind,title]) => <div key={kind}><div className="tree-heading">{link('/attestation/' + kind,title)}<button aria-label={'Подразделы: ' + title} aria-expanded={!!attOpen[kind]} onClick={() => setAttOpen(o => ({...o,[kind]:!o[kind]}))}><ChevronDown size={14}/></button></div>{attOpen[kind] && <div className="tree-branch">{link('/attestation/' + kind + '/commissions','Список комиссий')}{link('/attestation/' + kind + '/documents','Формирование и печать')}</div>}</div>)}</div>}
 <div className="tree-heading"><GraduationCap size={17}/>{link('/gek','Комиссии ГЭК')}<button aria-label="Подразделы ГЭК" aria-expanded={open.gek} onClick={() => setOpen(o => ({...o,gek:!o.gek}))}><ChevronDown size={14}/></button></div>
 {open.gek && <div className="tree-branch">{link('/commissions','Список комиссий',false)}{link('/gek/documents','Формирование и печать')}</div>}
 <div className="tree-heading"><Database size={17}/>{link('/data','Исходные данные')}<button aria-label="Подразделы исходных данных" aria-expanded={open.data} onClick={() => setOpen(o => ({...o,data:!o.data}))}><ChevronDown size={14}/></button></div>
 {open.data && <div className="tree-branch"><div className="tree-heading">{link('/data/people','Люди')}<button aria-label="Таблицы людей" aria-expanded={open.people} onClick={() => setOpen(o => ({...o,people:!o.people}))}><ChevronDown size={14}/></button></div>{open.people && <div className="tree-branch">{link('/data/catalog/teachers','Преподаватели')}{link('/data/people/external','Внешние члены ГЭК')}{link('/data/people/chairmen','Председатели ГЭК')}{link('/data/people/complex','Председатели комплексных ГЭК')}</div>}<div className="tree-heading">{link('/data/structure','Структура университета')}<button aria-label="Таблицы структуры" aria-expanded={open.structure} onClick={()=>setOpen(o=>({...o,structure:!o.structure}))}><ChevronDown size={14}/></button></div>{open.structure&&<div className="tree-branch">{link('/data/catalog/schools','Высшие школы')}</div>}<div className="tree-heading">{link('/data/education','Образование')}<button aria-label="Таблицы образования" aria-expanded={open.education} onClick={()=>setOpen(o=>({...o,education:!o.education}))}><ChevronDown size={14}/></button></div>{open.education&&<div className="tree-branch">{link('/data/catalog/directions','Направления подготовки')}{link('/data/catalog/programs','Образовательные программы')}{link('/data/catalog/disciplines','Дисциплины')}</div>}</div>}
 <div className="tree-heading"><Archive size={17}/>{link('/archive','Архив')}</div>
 </nav>;
}
