import { useState } from 'react';
import { Plus, Pencil, Trash2 } from 'lucide-react';
import { Field, Modal } from './ui';
import { oopTables, type OopRow } from '../data/oopForm';
import { makeClientId } from '../utils/id';
import { clone } from '../data/model';
export function OopMatrix({ kind, rows, onChange }: {kind:string; rows:OopRow[]; onChange:(rows:OopRow[])=>void}) {
 const schema=oopTables[kind];const [edit,setEdit]=useState<OopRow|null>(null);
 return <div className="oop-matrix"><div className="oop-matrix-heading"><h3>{schema.title}</h3><button type="button" className="button small secondary" onClick={()=>setEdit({id:makeClientId(),values:schema.columns.map(()=> '')})}><Plus size={15}/>Добавить</button></div><div className="people-table-shell"><div className="people-table-scroll"><table className="people-table"><thead><tr>{schema.columns.map(c=><th key={c}>{c}</th>)}<th>Действия</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{row.values.map((value,i)=><td key={i} style={{whiteSpace:'pre-line'}}>{value||'—'}</td>)}<td><div className="button-row"><button type="button" className="icon-button" aria-label={'Изменить запись '+(row.values[0]||'')} onClick={()=>setEdit(clone(row))}><Pencil size={15}/></button><button type="button" className="icon-button" aria-label={'Убрать запись '+(row.values[0]||'')} onClick={()=>onChange(rows.filter(r=>r.id!==row.id))}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>{!rows.length&&<p className="oop-empty">Записи не добавлены. Добавьте сведения для программы.</p>}</div>{edit&&<Modal wide title={schema.title} onClose={()=>setEdit(null)} footer={<><button className="button secondary" onClick={()=>setEdit(null)}>Отмена</button><button className="button primary" disabled={!edit.values.some(v=>v.trim())} onClick={()=>{onChange(rows.some(r=>r.id===edit.id)?rows.map(r=>r.id===edit.id?edit:r):[...rows,edit]);setEdit(null);}}>Применить</button></>}><div className="form-grid">{schema.columns.map((column,i)=><Field key={column} label={column}><textarea aria-label={column} rows={4} value={edit.values[i]??''} onChange={e=>setEdit({...edit,values:edit.values.map((v,j)=>j===i?e.target.value:v)})}/></Field>)}</div></Modal>}</div>;
}
