import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { ArrowRight, Check, ChevronRight, Search, X, Users, FileText, CircleHelp } from 'lucide-react';
import type { Person, Program } from '../data/model';
export function Brand({ compact = false }: { compact?: boolean }) { return <div className={`brand ${compact ? 'compact' : ''}`}><img className="official-logo" src="/polytech-logo.svg" alt="Санкт-Петербургский политехнический университет Петра Великого"/><div><strong>ИПМЭиТ</strong><span>Рабочая среда</span></div></div>; }
export function Avatar({ person, small = false }: { person?: Pick<Person, 'initials' | 'color'>; small?: boolean }) { return <span className={`avatar ${person?.color ?? 'sage'} ${small ? 'small' : ''}`} aria-hidden="true">{person?.initials ?? <Users size={16}/>}</span>; }
export function Badge({ ready }: { ready: boolean }) { return <span className={`badge ${ready ? 'ready' : 'draft'}`}><span/>{ready ? 'Заполнена' : 'На заполнении'}</span>; }
export function Empty({ title, children, action }: { title: string; children?: ReactNode; action?: ReactNode }) { return <div className="empty-state"><span className="empty-icon"><Search size={25}/></span><h3>{title}</h3><p>{children}</p>{action}</div>; }
export function Field({ label, hint, error, children, required }: { label: string; hint?: string; error?: string; children: ReactNode; required?: boolean }) { return <label className={`field ${error ? 'has-error' : ''}`}><span className="field-label">{label}{required && <span className="required"> *</span>}</span>{children}{error ? <span className="field-error">{error}</span> : hint && <span className="field-hint">{hint}</span>}</label>; }
export function Modal({ title, subtitle, onClose, children, footer, wide = false }: { title: string; subtitle?: string; onClose: () => void; children: ReactNode; footer?: ReactNode; wide?: boolean }) {
 const ref = useRef<HTMLDialogElement>(null); const headingId = useId(); const closeRef = useRef(onClose); closeRef.current = onClose;
 useEffect(() => { const previous = document.activeElement as HTMLElement | null; ref.current?.showModal(); const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = overflow; previous?.focus(); }; }, []);
 return createPortal(<dialog ref={ref} className={`modal ${wide ? 'wide' : ''}`} aria-labelledby={headingId} onCancel={e => { e.preventDefault(); closeRef.current(); }} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="modal-inner"><header className="modal-header"><div><h2 id={headingId}>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-button" aria-label="Закрыть окно" onClick={onClose}><X size={20}/></button></header><div className="modal-body">{children}</div>{footer && <footer className="modal-footer">{footer}</footer>}</div></dialog>, document.body);
}
export function Confirm({ title, children, confirmLabel, onConfirm, onClose, danger = false }: { title: string; children: ReactNode; confirmLabel: string; onConfirm: () => void; onClose: () => void; danger?: boolean }) { return <Modal title={title} onClose={onClose} footer={<><button className="button secondary" onClick={onClose}>Отмена</button><button className={`button ${danger ? 'danger' : 'primary'}`} onClick={onConfirm}>{confirmLabel}</button></>}><p className="confirm-copy">{children}</p></Modal>; }
export function Picker({ title, people, programs, selected, multiple, onApply, onClose, notice }: { title: string; people?: Person[]; programs?: Program[]; selected: string[]; multiple?: boolean; onApply: (ids: string[]) => void; onClose: () => void; notice?: string }) {
 const [query, setQuery] = useState(''); const [ids, setIds] = useState(selected.filter(Boolean));
 const items = (people ?? programs ?? []).filter(p => `${p.name} ${'organization' in p ? p.organization : p.code}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));
 const toggle = (id: string) => setIds(multiple ? ids.includes(id) ? ids.filter(x => x !== id) : [...ids, id] : [id]);
 return <Modal title={title} subtitle={multiple ? 'Можно выбрать несколько записей' : 'Выберите запись из справочника'} onClose={onClose} footer={<><span className="muted">Выбрано: {ids.length}</span><button className="button secondary" onClick={onClose}>Отмена</button><button className="button primary" disabled={!multiple && ids.length === 0} onClick={() => onApply(ids)}>Подтвердить <Check size={16}/></button></>}><div className="search-field picker-search"><Search size={18}/><input aria-label="Поиск в справочнике" placeholder={programs ? 'Название или код программы' : 'Имя, организация или фамилия'} value={query} onChange={e => setQuery(e.target.value)} autoFocus/></div>{notice && <p className="small-notice">{notice}</p>}<div className="picker-list">{items.map(p => <label className={`picker-option ${ids.includes(p.id) ? 'selected' : ''}`} key={p.id}><input type={multiple ? 'checkbox' : 'radio'} name="picker" checked={ids.includes(p.id)} onChange={() => toggle(p.id)}/>{'initials' in p ? <Avatar person={p}/> : <span className="program-icon"><FileText size={20}/></span>}<span><strong>{p.name}</strong><small>{'organization' in p ? `${p.position} · ${p.organization}` : `${p.code} · ${p.level}`}</small></span></label>)}{items.length === 0 && <Empty title="Ничего не найдено">Попробуйте другую фамилию или название.</Empty>}</div></Modal>;
}
export function Help({ onClose }: { onClose: () => void }) { return <Modal title="Работа с ГЭК" subtitle="От списка комиссий до готовой таблицы" onClose={onClose}><div className="help-steps">{[['Найдите или создайте комиссию', 'Используйте поиск, год и фильтр высшей школы. Новая комиссия появится в общем списке.'], ['Заполните карточку', 'Назначьте председателя и секретаря, добавьте участников и образовательные программы. Заполните сведения о председателе.'], ['Сохраните и сформируйте документ', 'Сохраните карточку, затем откройте вкладку «Документы». Общая таблица формируется из списка комиссий.']].map(([title, copy], i) => <div key={title}><span>{i + 1}</span><section><h3>{title}</h3><p>{copy}</p></section></div>)}</div><div className="info-note"><CircleHelp size={18}/><p>Вход: <strong>admin / 12345678</strong>.</p></div></Modal>; }
export function SectionHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="section-heading"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</div>; }
export function InlineLink({ children, onClick }: { children: ReactNode; onClick: () => void }) { return <button className="text-button" onClick={onClick}>{children}<ArrowRight size={16}/></button>; }
export function Breadcrumb({ label, onClick, current }: { label: string; onClick: () => void; current?: string }) { return <div className="breadcrumb"><button onClick={onClick}>{label}</button>{current && <><span aria-hidden="true">/</span><span>{current}</span></>}</div>; }



